<a href="https://colab.research.google.com/github/yunseo449/ESAA/blob/main/YB_0904_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [8]:
A = np.ones((5,3))
B = np.ones((3,2))
result = np.dot(A,B)

print(result)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [9]:
z = np.arange(11)
z[(z>3) & (z<8)] *= -1
print(z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

1번 : 파이썬 내장 sum의 경우 반복 가능한 값, 시작값 이라서 -1+0+1+2+3+4 = 9
<br>2번: numpy 내장함수는 두번째 인수 -1이 마지막 축을 의미해서 axis = -1을 의미, 그래서 결과는 np.sum([0, 1, 2, 3, 4], axis=-1) = 0+1+2+3+4 = 10

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

1. 각 원소를 자기 자신만큼 거듭제곱
2. 원소별 비트 이동
3. z < -z로 해석되는 비교
4. 1j : 허수를 의미, 정수 * 허수 = 오류 x
5. 두 번 나눗셈, 결과는 실수형
6.  파이썬&넘파이 배열 차이로 인한 오류
- 넘파이에서는 배열 연산자를 쓸 수 없어서 연속 비교가 안된다.

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

1. 0으로 나눌 수 없기 때문에 not a number // 파이썬에서는 오류 발생, np에서는 nan으로
2. //는 정수 나눗셈, 정수형에는 nan이 없음
3. nan을 정수로 잘못 표현해서 실수로 변환

In [10]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/tmp/ipykernel_5324/3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/tmp/ipykernel_5324/3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/tmp/ipykernel_5324/3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [11]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)

print(Z1)
print(Z2)

common = np.intersect1d(Z1,Z2)
print(common)

[3 1 2 1 5 9 4 0 6 3]
[9 1 5 4 0 3 2 7 1 4]
[0 1 2 3 4 5 9]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

결과 : False.
<br>좌변 : nan / 우변 : 1j


#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [12]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [13]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [14]:
z = np.random.uniform(0,10,10)

print(z - z%1)
print(z // 1)

[8. 8. 7. 3. 3. 9. 2. 1. 3. 0.]
[8. 8. 7. 3. 3. 9. 2. 1. 3. 0.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [15]:
z = np.zeros((5,5))
z += np.arange(5)
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [16]:
z= np.random.random(10)
z.sort()
print(z)

[0.23422328 0.24024527 0.25504709 0.61511227 0.71570321 0.72008358
 0.84594486 0.85410866 0.86539282 0.97524633]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [17]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal = np.array_equal(A,B)
print(equal)

False


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [18]:
z = np.random.random((10,2))
x,y = z[:,0], z[:,1]
a = np.sqrt(x**2+y**2)
b = np.arctan2(y,x)
print(a)
print(b)

[1.17645018 0.58305578 0.74157687 1.06015219 0.35298593 0.92081273
 0.87026222 1.06202443 1.10306405 1.0331426 ]
[0.95033699 1.30733067 0.23140419 0.89530413 0.18432194 0.46773009
 1.24492841 0.59222877 1.10093414 0.37972327]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [19]:
z = np.random.random(10)
z[z.argmax()] = 0
print(z)

[0.74560483 0.75919202 0.58299231 0.         0.12397391 0.8035249
 0.03282258 0.60073755 0.0075239  0.15829686]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [21]:
z = np.arange(100)
r = np.random.uniform(0,100)
index = (np.abs(z-r)).argmin()
print(z[index])

96


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [23]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [24]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [25]:
#1st column
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,0].argsort()])

[[8 5 7]
 [8 2 1]
 [5 3 8]]
[[5 3 8]
 [8 5 7]
 [8 2 1]]


In [28]:
#2nd column
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[1 8 5]
 [7 1 1]
 [1 1 4]]
[[7 1 1]
 [1 1 4]
 [1 8 5]]


In [29]:
#3rd column
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,2].argsort()])

[[5 2 4]
 [5 7 9]
 [1 4 5]]
[[5 2 4]
 [1 4 5]
 [5 7 9]]
